; generated by PrusaSlicer 2.5.0+win64 on 2023-01-04 at 20:08:05 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R1
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P6 R0
G1 E-1.5 F2400
M73 P9 R0
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
; printing object Shape-Cylinder id:0 copy 0
M73 P10 R0
G1 X121.1 Y106.589 F10800

G91; Switching to relative XYZ positioning!

G1 E1.50100 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.419999
M73 P11 R0
G1 F488
G1 X-0.175 Y-0.591 E0.01845
G1 X-0.120 Y-0.621 E0.01895
G1 X0.000 Y-0.754 E0.02257
G1 X0.105 Y-0.606 E0.01841
G1 X0.150 Y-0.491 E0.01539
G1 X0.251 Y-0.559 E0.01834
G1 X0.427 Y-0.629 E0.02277
M73 P12 R0
G1 X0.564 Y-0.572 E0.02403
G1 X0.569 Y-0.394 E0.02072
G1 X0.540 Y-0.272 E0.01812
G1 X0.598 Y-0.177 E0.01868
G1 X0.612 Y-0.117 E0.01865
G1 X0.580 Y0.005 E0.01738
G1 X0.500 Y0.041 E0.01501
G1 X0.589 Y0.139 E0.01812
M73 P13 R0
G1 X0.751 Y0.327 E0.02454
G1 X0.665 Y0.457 E0.02417
G1 X0.429 Y0.436 E0.01831
G1 X0.390 Y0.485 E0.01864
G1 X0.286 Y0.548 E0.01851
G1 X0.235 Y0.585 E0.01887
G1 X0.143 Y0.746 E0.02276
M73 P14 R0
G1 X0.002 Y0.406 E0.01216
G1 X-0.032 Y0.655 E0.01961
G1 X-0.128 Y0.584 E0.01790
G1 X-0.239 Y0.576 E0.01868
G1 X-0.294 Y0.549 E0.01864
G1 X-0.521 Y0.632 E0.02454
G1 X-0.472 Y0.389 E0.01830
G1 X-0.517 Y0.347 E0.01865
M73 P15 R0
G1 X-0.536 Y0.222 E0.01738
G1 X-0.476 Y0.157 E0.01501
G1 X-0.597 Y0.102 E0.01812
G1 X-0.819 Y-0.007 E0.02454
G1 X-0.803 Y-0.163 E0.02454
G1 X-0.572 Y-0.229 E0.01845
G1 X-0.531 Y-0.317 E0.01851
G1 X-0.501 Y-0.381 E0.01884
M73 P16 R0
G1 X-0.418 Y-0.437 E0.01812
G1 X-0.344 Y-0.520 E0.01868
G1 X-0.263 Y-0.498 E0.01685
M204 S1000
G1 X-0.382 Y0.081 F10800
M204 S800
;TYPE:External perimeter
G1 F488
G1 X-0.183 Y-0.618 E0.01929
G1 X-0.135 Y-0.702 E0.02141
G1 X0.000 Y-0.806 E0.02415
G1 X0.128 Y-0.721 E0.02191
M73 P17 R0
G1 X0.150 Y-0.479 E0.01504
G1 X0.278 Y-0.619 E0.02032
G1 X0.461 Y-0.681 E0.02461
G1 X0.608 Y-0.615 E0.02590
G1 X0.623 Y-0.433 E0.02273
G1 X0.601 Y-0.303 E0.02014
G1 X0.625 Y-0.185 E0.01952
M73 P18 R0
G1 X0.694 Y-0.133 E0.02116
G1 X0.608 Y0.006 E0.01822
G1 X0.556 Y0.046 E0.01668
G1 X0.654 Y0.154 E0.02014
G1 X0.811 Y0.352 E0.02646
G1 X0.725 Y0.499 E0.02634
G1 X0.454 Y0.462 E0.01939
G1 X0.443 Y0.550 E0.02115
M73 P19 R0
G1 X0.298 Y0.573 E0.01935
G1 X0.266 Y0.662 E0.02135
G1 X0.155 Y0.807 E0.02461
G1 X0.003 Y0.616 E0.01846
G1 X-0.037 Y0.534 E0.01601
G1 X-0.142 Y0.649 E0.01990
G1 X-0.249 Y0.602 E0.01952
M73 P20 R0
G1 X-0.334 Y0.623 E0.02116
G1 X-0.562 Y0.682 E0.02647
G1 X-0.500 Y0.412 E0.01939
G1 X-0.587 Y0.393 E0.02116
G1 X-0.562 Y0.233 E0.01822
G1 X-0.529 Y0.175 E0.01668
G1 X-0.663 Y0.114 E0.02014
G1 X-0.884 Y-0.008 E0.02646
M73 P21 R0
G1 X-0.592 Y-0.121 E0.01810
G1 X-0.536 Y-0.151 E0.01668
G1 X-0.614 Y-0.276 E0.02016
G1 X-0.446 Y-0.301 E0.01609
G1 X-0.431 Y-0.338 E0.01640
G1 X-0.465 Y-0.486 E0.02014
G1 X-0.360 Y-0.543 E0.01952
M73 P22 R0
G1 X-0.302 Y-0.572 E0.01936
M204 S1000
G1 X0.223 Y-0.365 F10800
G1 E-0.07500 F2400
;WIPE_START
G1 F8640
G1 X-0.434 Y-0.306 E-0.18555
G1 X-0.135 Y-0.702 E-0.18867
G1 X0.000 Y-0.806 E-0.21281
G1 X0.128 Y-0.721 E-0.19312
G1 X0.150 Y-0.479 E-0.13251
G1 X0.278 Y-0.619 E-0.17910
G1 X0.461 Y-0.681 E-0.21691
G1 X0.120 Y-0.121 E-0.04507
;WIPE_END
G1 E-0.07125 F2400
G1 X5.337 Y-0.596 F10800
G1 E1.50100 F2400
M204 S800
;TYPE:Solid infill
;WIDTH:0.434236
G1 F488
G1 X1.163 Y1.164 E0.05113
G1 X0.219 Y0.301 E0.01157
M73 P23 R0
G1 X0.365 Y0.701 E0.02454
G1 X0.071 Y0.206 E0.00677
G1 X-2.470 Y-2.470 E0.10854
G1 X-0.433 Y-0.125 E0.01400
M73 P24 R0
G1 X-0.292 Y-0.046 E0.00917
G1 X3.355 Y3.354 E0.14741
G1 X0.026 Y0.138 E0.00436
M73 P25 R0
G1 X0.002 Y0.444 E0.01380
G1 X-3.955 Y-3.956 E0.17383
G1 X-0.314 Y-0.002 E0.00974
M73 P26 R0
G1 X-0.213 Y0.030 E0.00668
G1 X4.456 Y4.455 E0.19580
G1 X-0.096 Y0.458 E0.01454
M73 P27 R0
G1 X-4.806 Y-4.806 E0.21120
G1 X-0.426 Y0.127 E0.01384
M73 P29 R0
G1 X5.082 Y5.082 E0.22334
G1 X-0.162 Y0.391 E0.01316
M73 P30 R0
G1 X-5.303 Y-5.302 E0.23302
G1 X-0.347 Y0.206 E0.01255
M73 P32 R0
G1 X5.446 Y5.446 E0.23932
G1 X-0.249 Y0.304 E0.01222
M73 P33 R0
G1 X-5.514 Y-5.514 E0.24230
M73 P34 R0
G1 X-0.277 Y0.276 E0.01216
M73 P35 R0
G1 X5.539 Y5.540 E0.24344
G1 X-0.303 Y0.250 E0.01222
M73 P37 R0
G1 X-5.511 Y-5.511 E0.24216
G1 X-0.223 Y0.330 E0.01238
M73 P38 R0
G1 X5.428 Y5.428 E0.23854
G1 X-0.352 Y0.202 E0.01260
M73 P40 R0
G1 X-5.291 Y-5.291 E0.23251
G1 X-0.172 Y0.381 E0.01299
M73 P42 R0
G1 X5.072 Y5.072 E0.22290
G1 X-0.286 Y0.119 E0.00963
M73 P43 R0
G1 X-0.119 Y0.029 E0.00381
G1 X-4.803 Y-4.803 E0.21107
G1 X-0.094 Y0.460 E0.01459
M73 P44 R0
G1 X4.437 Y4.437 E0.19494
M73 P45 R0
G1 X-0.191 Y0.026 E0.00598
M73 P46 R0
G1 X-0.339 Y-0.003 E0.01053
G1 X-3.934 Y-3.933 E0.17287
G1 X0.000 Y0.382 E0.01189
M73 P47 R0
G1 X0.028 Y0.199 E0.00624
G1 X3.317 Y3.317 E0.14576
G1 X-0.599 Y-0.122 E0.01900
M73 P48 R0
G1 X-0.120 Y-0.044 E0.00396
G1 X-2.404 Y-2.404 E0.10564
G1 X0.055 Y0.186 E0.00600
M73 P49 R0
G1 X0.158 Y0.339 E0.01163
G1 X0.436 Y0.658 E0.02454
G1 X1.103 Y1.123 E0.04892
M204 S1000
; stop printing object Shape-Cylinder id:0 copy 0
M106 S201.45
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


G1 E-0.07500 F2400
;WIPE_START
G1 F8640
G1 X-1.103 Y-1.123 E-0.41542
G1 X-0.436 Y-0.658 E-0.20842
M73 P50 R0
G1 X-0.158 Y-0.339 E-0.09874
G1 X-0.055 Y-0.186 E-0.05096
G1 X1.555 Y1.555 E-0.58021
;WIPE_END
G1 E-0.07125 F2400
G1 Z-Infinity F720
;AFTER_LAYER_CHANGE
;0.4
M104 S210 ; set temperature
; printing object Shape-Cylinder id:0 copy 0
G1 X0.371 Y1.136 F10800
G1 E1.50100 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.449999
G1 F520
G1 X-0.740 Y-0.418 E0.02748
G1 X-0.636 Y-0.544 E0.02705
G1 X-0.395 Y-0.497 E0.02052
G1 X-0.349 Y-0.541 E0.02082
G1 X-0.221 Y-0.561 E0.01950
M73 P51 R0
G1 X-0.154 Y-0.496 E0.01678
G1 X-0.096 Y-0.619 E0.02026
G1 X0.022 Y-0.850 E0.02748
G1 X0.128 Y-0.576 E0.01907
G1 X0.150 Y-0.497 E0.01678
G1 X0.268 Y-0.569 E0.02034
G1 X0.328 Y-0.469 E0.01850
G1 X0.416 Y-0.489 E0.02074
G1 X0.501 Y-0.398 E0.02070
M73 P52 R0
G1 X0.550 Y-0.356 E0.02116
G1 X0.725 Y-0.293 E0.02529
G1 X0.715 Y-0.147 E0.02360
G1 X0.594 Y-0.040 E0.01925
G1 X0.866 Y0.097 E0.02816
G1 X0.562 Y0.177 E0.01904
G1 X0.482 Y0.192 E0.01678
G1 X0.542 Y0.316 E0.02026
M73 P53 R0
G1 X0.646 Y0.552 E0.02748
G1 X0.395 Y0.497 E0.02052
G1 X0.349 Y0.541 E0.02082
G1 X0.317 Y0.803 E0.02791
G1 X0.114 Y0.634 E0.02082
G1 X0.049 Y0.633 E0.02052
G1 X-0.071 Y0.623 E0.02027
G1 X-0.137 Y0.640 E0.02116
M73 P54 R0
G1 X-0.306 Y0.720 E0.02529
G1 X-0.345 Y0.536 E0.02059
G1 X-0.346 Y0.412 E0.01741
G1 X-0.460 Y0.426 E0.02026
G1 X-0.717 Y0.456 E0.02748
G1 X-0.591 Y0.233 E0.02052
G1 X-0.620 Y0.176 E0.02083
G1 X-0.646 Y0.051 E0.02096
M73 P55 R0
G1 X-0.644 Y-0.014 E0.02082
G1 X-0.633 Y-0.140 E0.02096
G1 X-0.555 Y-0.182 E0.01888
M204 S1000
G1 X-0.231 Y0.350 F10800
M204 S800
;TYPE:External perimeter
G1 F520
G1 X-0.800 Y-0.452 E0.02973
G1 X-0.696 Y-0.595 E0.02958
G1 X-0.420 Y-0.527 E0.02179
G1 X-0.398 Y-0.618 E0.02375
M73 P56 R0
G1 X-0.232 Y-0.589 E0.02048
G1 X-0.172 Y-0.553 E0.01873
G1 X-0.107 Y-0.692 E0.02261
G1 X0.025 Y-0.919 E0.02973
G1 X0.136 Y-0.614 E0.02033
G1 X0.167 Y-0.555 E0.01873
G1 X0.298 Y-0.633 E0.02264
G1 X0.345 Y-0.492 E0.01942
M73 P57 R0
G1 X0.472 Y-0.555 E0.02356
G1 X0.525 Y-0.418 E0.02168
G1 X0.624 Y-0.404 E0.02403
G1 X0.515 Y-0.208 E0.01796
G1 X0.539 Y-0.175 E0.01830
G1 X0.509 Y-0.094 E0.01673
G1 X0.666 Y-0.044 E0.02157
G1 X0.935 Y0.104 E0.03042
M73 P58 R0
G1 X0.599 Y0.189 E0.02033
G1 X0.539 Y0.215 E0.01873
G1 X0.604 Y0.352 E0.02261
G1 X0.699 Y0.598 E0.02972
G1 X0.420 Y0.527 E0.02179
G1 X0.398 Y0.617 E0.02375
G1 X0.339 Y0.860 E0.02987
G1 X0.129 Y0.723 E0.02375
M73 P59 R0
G1 X0.053 Y0.672 E0.02179
G1 X-0.075 Y0.662 E0.02153
G1 X-0.156 Y0.727 E0.02403
G1 X-0.328 Y0.773 E0.02713
G1 X-0.417 Y0.640 E0.02470
G1 X-0.341 Y0.400 E0.01698
G1 X-0.513 Y0.475 E0.02261
M73 P60 R0
G1 X-0.776 Y0.494 E0.02972
G1 X-0.627 Y0.247 E0.02179
G1 X-0.707 Y0.200 E0.02375
G1 X-0.676 Y0.053 E0.02193
G1 X-0.735 Y-0.015 E0.02375
G1 X-0.662 Y-0.146 E0.02193
G1 X-0.641 Y-0.211 E0.02181
M204 S1000
M73 P61 R0
G1 X-0.093 Y-0.417 F10800
G1 E-0.07500 F2400
;WIPE_START
G1 F8640
G1 X-0.764 Y-0.054 E-0.25821
G1 X-0.696 Y-0.595 E-0.24149
G1 X-0.420 Y-0.527 E-0.17788
G1 X-0.398 Y-0.618 E-0.19384
G1 X-0.232 Y-0.589 E-0.16716
G1 X-0.172 Y-0.553 E-0.15291
G1 X-0.094 Y-0.608 E-0.16225
;WIPE_END
G1 E-0.07125 F2400
G1 X8.463 Y1.634 F10800
G1 E1.50100 F2400
;TYPE:Top solid infill
;WIDTH:0.413722
G1 F520
G1 X-0.947 Y0.947 E0.03943
G1 X-0.236 Y0.205 E0.00920
M73 P62 R0
G1 X-0.676 Y0.431 E0.02362
G1 X-0.409 Y0.162 E0.01295
G1 X2.367 Y-2.368 E0.09858
G1 X0.078 Y-0.184 E0.00590
M73 P63 R0
G1 X0.102 Y-0.380 E0.01156
G1 X0.018 Y-0.158 E0.00470
G1 X-3.312 Y3.312 E0.13794
G1 X-0.570 Y0.045 E0.01681
M73 P64 R0
G1 X3.950 Y-3.949 E0.16445
G1 X-0.030 Y-0.495 E0.01459
M73 P65 R0
G1 X-4.440 Y4.440 E0.18488
G1 X-0.440 Y-0.084 E0.01319
M73 P66 R0
G1 X4.825 Y-4.825 E0.20092
G1 X-0.061 Y-0.261 E0.00790
M73 P67 R0
G1 X-0.057 Y-0.146 E0.00460
G1 X-5.136 Y5.137 E0.21389
G1 X-0.382 Y-0.143 E0.01199
M73 P69 R0
G1 X5.370 Y-5.370 E0.22360
G1 X-0.096 Y-0.243 E0.00769
M73 P70 R0
G1 X-0.068 Y-0.118 E0.00400
G1 X-5.541 Y5.541 E0.23073
G1 X-0.335 Y-0.189 E0.01133
M73 P72 R0
G1 X5.671 Y-5.670 E0.23611
G1 X-0.233 Y-0.293 E0.01099
M73 P73 R0
G1 X-5.725 Y5.726 E0.23841
G1 X-0.283 Y-0.242 E0.01095
M73 P75 R0
G1 X5.766 Y-5.766 E0.24011
G1 X-0.283 Y-0.241 E0.01095
M73 P76 R0
G1 X-5.725 Y5.725 E0.23841
M73 P77 R0
G1 X-0.232 Y-0.292 E0.01099
M73 P78 R0
G1 X5.673 Y-5.674 E0.23625
G1 X-0.323 Y-0.201 E0.01121
M73 P80 R0
G1 X-5.556 Y5.556 E0.23138
G1 X-0.068 Y-0.118 E0.00402
M73 P81 R0
G1 X-0.096 Y-0.242 E0.00767
G1 X5.369 Y-5.369 E0.22357
G1 X-0.395 Y-0.130 E0.01224
M73 P83 R0
G1 X-5.122 Y5.122 E0.21329
G1 X-0.057 Y-0.146 E0.00462
M73 P84 R0
G1 X-0.061 Y-0.260 E0.00788
G1 X4.841 Y-4.841 E0.20158
G1 X-0.472 Y-0.053 E0.01398
M73 P85 R0
G1 X-4.439 Y4.440 E0.18487
G1 X0.000 Y-0.525 E0.01546
M73 P87 R0
G1 X3.948 Y-3.948 E0.16438
G1 X-0.240 Y0.009 E0.00708
M73 P88 R0
G1 X-0.341 Y0.048 E0.01014
G1 X-3.309 Y3.309 E0.13779
G1 X0.126 Y-0.567 E0.01709
M73 P89 R0
G1 X0.051 Y-0.135 E0.00426
G1 X2.393 Y-2.392 E0.09961
G1 X-0.434 Y0.175 E0.01376
G1 X-0.340 Y0.196 E0.01156
M73 P90 R0
G1 X-0.598 Y0.476 E0.02252
G1 X-0.906 Y0.906 E0.03774
; stop printing object Shape-Cylinder id:0 copy 0

G90; Returning to absolute XYZ positioning!

G1 E-.075 F2400
;WIPE_START
G1 F8640;_WIPE
G1 X122.193 Y102.039 E-.33822
G1 F8640;_WIPE
G1 X122.791 Y101.563 E-.20178
G1 F8640;_WIPE
G1 X123.131 Y101.367 E-.10363
G1 F8640;_WIPE
G1 X123.565 Y101.192 E-.12333
G1 F8640;_WIPE
G1 X121.992 Y102.764 E-.58678
;WIPE_END
G1 E-.07125 F2400
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.4 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
; filament used [mm] = 12.29
; filament used [cm3] = 0.03
; filament used [g] = 0.04
; filament cost = 0.00
; total filament used [g] = 0.04
; total filament cost = 0.00
; estimated printing time (normal mode) = 1m 2s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.955
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #F00000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Eryone Red"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA_RedEryone_LWW
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = smoothie
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"Prusament PLA";"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 80
; max_layer_height = 0.3
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 10
; min_feature_size = 25%
; min_layer_height = 0.05
; min_print_speed = 5
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = LWW Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 5%
; retract_layer_change = 1
; retract_length = 1.5
; retract_length_toolchange = 4
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0.001
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 25
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 24
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
