; generated by PrusaSlicer 2.5.0+win64 on 2023-02-09 at 21:44:40 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P11 R0
M73 Q11 S0
G1 E-1.5 F2400
M73 P18 R0
M73 Q18 S0
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
; printing object Shape-Cylinder id:0 copy 0
G1 X126.395 Y105.959 F10800
G1 E1.501 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.419999
M73 P21 R0
M73 Q22 S0
G1 F300
G1 X126.33 Y106.062 E.00366
G1 X125.957 Y106.417 E.01543
G1 X125.507 Y106.624 E.01482
G1 X125.015 Y106.709 E.01495
G1 X124.501 Y106.632 E.01556
M73 P22 R0
M73 Q23 S0
G1 X124.032 Y106.408 E.01556
G1 X123.791 Y106.209 E.00937
G1 X123.507 Y105.817 E.0145
M73 P23 R0
G1 X123.325 Y105.339 E.01532
M73 Q24 S0
G1 X123.303 Y104.822 E.01549
G1 X123.389 Y104.488 E.01031
G1 X123.517 Y104.165 E.01042
M73 P24 R0
M73 Q25 S0
G1 X123.781 Y103.802 E.01343
G1 X124.199 Y103.493 E.01556
G1 X124.688 Y103.32 E.01554
G1 X125.005 Y103.29 E.00955
M73 P25 R0
M73 Q26 S0
G1 X125.507 Y103.375 E.01523
G1 X125.943 Y103.575 E.01437
G1 X126.326 Y103.926 E.01555
M73 P26 R0
G1 X126.59 Y104.374 E.01556
M73 Q27 S0
G1 X126.681 Y104.808 E.01329
G1 X126.697 Y105.178 E.0111
G1 X126.567 Y105.681 E.01556
M73 P27 R0
M73 Q28 S0
G1 X126.426 Y105.908 E.00798
M204 S1000
G1 X126.732 Y106.168 F10800
M204 S800
;TYPE:External perimeter
G1 F300
G1 X126.331 Y106.598 E.0176
G1 X125.996 Y106.825 E.01212
M73 P28 R0
G1 X125.567 Y106.999 E.01385
M73 Q29 S0
G1 X125.005 Y107.089 E.01705
G1 X124.39 Y106.997 E.01863
G1 X123.828 Y106.729 E.01863
M73 P29 R0
M73 Q30 S0
G1 X123.657 Y106.588 E.00664
G1 X123.268 Y106.168 E.01712
G1 X123.074 Y105.809 E.01223
M73 P30 R0
G1 X122.951 Y105.403 E.01272
M73 Q31 S0
G1 X122.924 Y104.782 E.01861
G1 X123.079 Y104.179 E.01863
M73 P31 R0
G1 X123.185 Y103.985 E.00664
M73 Q32 S0
G1 X123.52 Y103.527 E.01698
G1 X124.02 Y103.157 E.01863
G1 X124.606 Y102.949 E.01863
M73 P32 R0
M73 Q33 S0
G1 X125.188 Y102.93 E.01742
G1 X125.65 Y103.025 E.01414
G1 X126.164 Y103.266 E.01698
M73 P33 R0
M73 Q34 S0
G1 X126.623 Y103.686 E.01863
G1 X126.839 Y104.054 E.01279
G1 X126.994 Y104.409 E.0116
M73 P34 R0
G1 X127.058 Y104.792 E.0116
M73 Q35 S0
G1 X127.076 Y105.218 E.01279
G1 X126.921 Y105.821 E.01863
G1 X126.76 Y106.115 E.01004
M204 S1000
M73 P35 R0
M73 Q36 S0
G1 X126.334 Y106.131 F10800
G1 E-.075 F2400
;WIPE_START
G1 F8640
G1 X126.331 Y106.598 E-.1705
G1 X125.996 Y106.825 E-.10681
G1 X125.567 Y106.999 E-.12206
G1 X125.005 Y107.089 E-.15024
G1 X124.39 Y106.997 E-.1642
G1 X123.828 Y106.729 E-.1642
G1 X123.657 Y106.588 E-.05848
G1 X123.268 Y106.168 E-.15091
M73 P36 R0
G1 X123.074 Y105.809 E-.10778
G1 X122.951 Y105.403 E-.11207
G1 X122.943 Y105.227 E-.04652
;WIPE_END
G1 E-.07125 F2400
G1 X125.461 Y103.479 F10800
G1 E1.501 F2400
M204 S800
;TYPE:Solid infill
;WIDTH:0.445165
M73 Q37 S0
G1 F300
G1 X126.128 Y104.146 E.03012
G1 X126.329 Y104.487 E.01266
M73 P37 R0
G1 X126.394 Y104.706 E.0073
M73 Q38 S0
G1 X126.406 Y104.993 E.00917
G1 X124.989 Y103.576 E.06403
G1 X124.749 Y103.598 E.00768
M73 P38 R0
M73 Q39 S0
G1 X124.523 Y103.679 E.00768
M73 P39 R0
G1 X126.326 Y105.482 E.08149
M73 Q40 S0
G1 X126.302 Y105.577 E.00312
M73 P40 R0
M73 Q41 S0
G1 X126.133 Y105.858 E.01047
G1 X124.154 Y103.878 E.0894
M73 P41 R0
G1 X123.977 Y104.009 E.007
M73 P42 R0
M73 Q43 S0
G1 X123.859 Y104.153 E.00595
G1 X125.847 Y106.141 E.08983
G1 X125.554 Y106.314 E.01088
M73 P44 R0
M73 Q45 S0
G1 X125.475 Y106.338 E.00263
G1 X123.67 Y104.532 E.08155
G1 X123.587 Y104.852 E.01053
M73 P46 R0
M73 Q47 S0
G1 X123.595 Y105.026 E.00558
G1 X124.987 Y106.419 E.0629
G1 X124.585 Y106.359 E.013
M73 P47 R0
M73 Q48 S0
G1 X124.185 Y106.168 E.01414
M73 P48 R0
G1 X123.49 Y105.49 E.03103
M204 S1000
; stop printing object Shape-Cylinder id:0 copy 0
M106 S204
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


M73 Q49 S0
G1 E-.075 F2400
;WIPE_START
M73 P49 R0
G1 F8640
G1 X124.185 Y106.168 E-.25639
G1 X124.585 Y106.359 E-.11678
G1 X124.987 Y106.419 E-.10743
G1 X123.595 Y105.026 E-.51967
G1 X123.587 Y104.852 E-.04614
M73 Q50 S0
G1 X123.67 Y104.532 E-.08702
G1 X124.26 Y105.123 E-.22032
;WIPE_END
G1 E-.07125 F2400
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.4
M104 S210 ; set temperature
; printing object Shape-Cylinder id:0 copy 0
G1 X126.841 Y105.239 F10800
G1 E1.501 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.449999
M73 P50 R0
G1 F300
G1 X126.722 Y105.713 E.01582
G1 X126.426 Y106.196 E.01831
M73 Q51 S0
G1 X126.014 Y106.561 E.01778
G1 X125.513 Y106.789 E.01779
M73 P51 R0
G1 X125.141 Y106.838 E.01213
M73 Q52 S0
G1 X124.761 Y106.841 E.01227
G1 X124.287 Y106.722 E.01582
M73 P52 R0
G1 X123.792 Y106.419 E.01875
G1 X123.54 Y106.158 E.01173
M73 Q53 S0
G1 X123.349 Y105.819 E.01257
G1 X123.203 Y105.468 E.01227
M73 P53 R0
G1 X123.137 Y104.984 E.01582
G1 X123.23 Y104.425 E.01831
M73 Q54 S0
G1 X123.483 Y103.918 E.01831
M73 P54 R0
G1 X123.844 Y103.547 E.01674
G1 X124.287 Y103.278 E.01674
M73 Q55 S0
G1 X124.838 Y103.146 E.01831
G1 X125.403 Y103.181 E.01831
M73 P55 R0
G1 X125.713 Y103.278 E.01051
M73 Q56 S0
G1 X126.196 Y103.574 E.01831
G1 X126.561 Y103.986 E.01778
M73 P56 R0
G1 X126.789 Y104.487 E.01778
M73 Q57 S0
G1 X126.838 Y104.859 E.01213
G1 X126.841 Y105.179 E.01033
M204 S1000
M73 P57 R0
G1 X127.246 Y105.285 F10800
M204 S800
;TYPE:External perimeter
G1 F300
G1 X127.224 Y105.473 E.00612
G1 X127.095 Y105.883 E.01392
G1 X126.741 Y106.461 E.02189
M73 Q58 S0
G1 X126.238 Y106.906 E.02172
M73 P58 R0
G1 X125.626 Y107.185 E.02172
M73 Q59 S0
G1 X124.955 Y107.273 E.02189
G1 X124.527 Y107.224 E.01392
M73 P59 R0
G1 X124.117 Y107.095 E.01392
M73 Q60 S0
G1 X123.535 Y106.739 E.02204
G1 X123.211 Y106.403 E.01508
M73 P60 R0
G1 X122.876 Y105.81 E.02204
M73 Q61 S0
G1 X122.761 Y105.395 E.01391
G1 X122.727 Y104.966 E.01392
M73 P61 R0
G1 X122.839 Y104.298 E.02189
G1 X123.141 Y103.692 E.02189
M73 Q62 S0
G1 X123.42 Y103.364 E.01392
M73 P62 R0
G1 X123.762 Y103.093 E.01409
G1 X124.143 Y102.894 E.01392
M73 Q63 S0
G1 X124.802 Y102.736 E.02189
M73 P63 R0
G1 X125.478 Y102.777 E.0219
G1 X125.883 Y102.905 E.01374
M73 Q64 S0
G1 X126.461 Y103.259 E.02189
M73 P64 R0
G1 X126.906 Y103.762 E.02172
G1 X127.185 Y104.374 E.02172
M73 Q65 S0
G1 X127.273 Y105.045 E.02189
M73 P65 R0
G1 X127.252 Y105.225 E.00586
M204 S1000
M73 Q66 S0
G1 X127.077 Y105.37 F10800
G1 E-.075 F2400
;WIPE_START
G1 F8640
G1 X127.224 Y105.473 E-.06578
G1 X127.095 Y105.883 E-.11361
G1 X126.741 Y106.461 E-.17873
M73 P66 R0
G1 X126.238 Y106.906 E-.17729
G1 X125.626 Y107.185 E-.17731
G1 X124.955 Y107.273 E-.17871
G1 X124.527 Y107.224 E-.1136
G1 X124.117 Y107.095 E-.1136
G1 X123.535 Y106.739 E-.17992
G1 X123.39 Y106.588 E-.0552
;WIPE_END
G1 E-.07125 F2400
G1 X125.569 Y106.632 F10800
G1 E1.501 F2400
;TYPE:Top solid infill
;WIDTH:0.433366
M73 Q67 S0
G1 F300
G1 X126.243 Y105.958 E.02957
G1 X126.465 Y105.596 E.01315
M73 P67 R0
G1 X126.549 Y105.329 E.00868
M73 Q68 S0
G1 X126.578 Y105.07 E.00808
G1 X125.086 Y106.562 E.06542
M73 P68 R0
G1 X124.949 Y106.58 E.00429
M73 P69 R0
M73 Q69 S0
G1 X124.671 Y106.549 E.00868
G1 X124.577 Y106.519 E.00304
G1 X126.517 Y104.565 E.08536
M73 Q70 S0
G1 X126.348 Y104.196 E.01258
M73 P71 R0
M73 Q71 S0
G1 X124.203 Y106.342 E.09407
G1 X123.969 Y106.198 E.0085
M73 P73 R0
M73 Q73 S0
G1 X123.883 Y106.109 E.00384
G1 X126.102 Y103.89 E.09729
G1 X126.014 Y103.791 E.0041
M73 P75 R0
M73 Q75 S0
G1 X125.787 Y103.653 E.00824
G1 X123.653 Y105.787 E.0936
M73 Q76 S0
G1 X123.515 Y105.545 E.00864
M73 P77 R0
M73 Q77 S0
G1 X123.478 Y105.41 E.00434
G1 X125.411 Y103.477 E.08475
M73 Q78 S0
G1 X125.352 Y103.458 E.00192
M73 P79 R0
M73 Q79 S0
G1 X124.905 Y103.431 E.01389
G1 X123.435 Y104.901 E.06446
G1 X123.5 Y104.512 E.01222
M73 P80 R0
M73 Q81 S0
G1 X123.718 Y104.074 E.0152
M73 P81 R0
G1 X124.412 Y103.371 E.03062
; stop printing object Shape-Cylinder id:0 copy 0
G1 E-.075 F2400
;WIPE_START
M73 P82 R0
M73 Q82 S0
G1 F8640;_WIPE
G1 X123.718 Y104.074 E-.26062
G1 F8640;_WIPE
G1 X123.5 Y104.512 E-.12933
G1 F8640;_WIPE
G1 X123.435 Y104.901 E-.10398
G1 F8640;_WIPE
G1 X124.905 Y103.431 E-.54867
G1 F8640;_WIPE
G1 X125.352 Y103.458 E-.11818
G1 F8640;_WIPE
G1 X125.411 Y103.477 E-.01636
G1 F8640;_WIPE
G1 X124.938 Y103.95 E-.17659
;WIPE_END
G1 E-.07125 F2400
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.4 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 2.99
; filament used [cm3] = 0.01
; filament used [g] = 0.01
; filament cost = 0.00
; total filament used [g] = 0.01
; total filament cost = 0.00
; estimated printing time (normal mode) = 33s
; estimated printing time (silent mode) = 33s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.955
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #F00000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Eryone Red"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA_RedEryone_LWW
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"Prusament PLA";"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 80
; max_layer_height = 0.3
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 10
; min_feature_size = 25%
; min_layer_height = 0.05
; min_print_speed = 5
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = LWW Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 5%
; retract_layer_change = 1
; retract_length = 1.5
; retract_length_toolchange = 4
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0.001
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 25
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 24
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
