; generated by PrusaSlicer 2.5.0+win64 on 2023-02-09 at 23:09:39 UTC

; 

; external perimeters extrusion width = 0.45mm
; perimeters extrusion width = 0.45mm
; infill extrusion width = 0.45mm
; solid infill extrusion width = 0.45mm
; top infill extrusion width = 0.40mm
; first layer extrusion width = 0.42mm

M73 P0 R0
M73 Q0 S0
M201 X1000 Y1000 Z200 E5000 ; sets maximum accelerations, mm/sec^2
M203 X200 Y200 Z12 E120 ; sets maximum feedrates, mm / sec
M204 P1250 R1250 T1250 ; sets acceleration (P, T) and retract acceleration (R), mm/sec^2
M205 X8.00 Y8.00 Z0.40 E4.50 ; sets the jerk limits, mm/sec
M205 S0 T0 ; sets the minimum extruding and travel feed rate, mm/sec
M107
;TYPE:Custom
M862.3 P "MK3S" ; printer model check
M862.1 P0.4 ; nozzle diameter check
M115 U3.9.3 ; tell printer latest fw version
G90 ; use absolute coordinates
M83 ; extruder relative mode
M104 S215 ; set extruder temp
M140 S60 ; set bed temp
M190 S60 ; wait for bed temp
M109 S215 ; wait for extruder temp
G28 W ; home all without mesh bed level
G80 ; mesh bed leveling
G1 Y-3.0 F1000.0 ; go outside print area
G92 E0.0
G1 X60.0 E9.0 F1000.0 ; intro line
G1 X100.0 E12.5 F1000.0 ; intro line
G92 E0.0
M221 S95

; Don't change E values below. Excessive value can damage the printer.
M907 E430 ; set extruder motor current
G21 ; set units to millimeters
G90 ; use absolute coordinates
M83 ; use relative distances for extrusion
M900 K30 ; Filament gcode
M107
;LAYER_CHANGE
;Z:0.2
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.2


M73 P7 R0
M73 Q7 S0
G1 E-1.5 F2400
M73 P12 R0
M73 Q12 S0
G1 Z.2 F720
;AFTER_LAYER_CHANGE
;0.2
; printing object ThinSewingLineLonger.stl id:0 copy 0
M73 P13 R0
G1 X124.885 Y104.857 F10800
G1 E1.501 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.444351
M73 P14 R0
M73 Q15 S0
G1 F300
G1 X125.079 Y104.799 E.00643
G1 X144.922 Y104.807 E.63254
;WIDTH:0.439523
G1 X145.014 Y104.807 E.00291
;WIDTH:0.434636
M73 P23 R0
M73 Q23 S0
G1 X145.158 Y104.885 E.0051
G1 X145.191 Y105.03 E.00463
G1 X145.115 Y105.158 E.00463
;WIDTH:0.439523
M73 Q24 S0
G1 X144.922 Y105.203 E.00625
;WIDTH:0.444351
G1 X125.079 Y105.201 E.63254
G1 X124.888 Y105.154 E.00626
M73 P31 R0
M73 Q32 S0
G1 X124.809 Y105 E.00552
G1 X124.857 Y104.91 E.00326
M204 S1000
M73 P32 R0
G1 X124.746 Y104.481 F10800
M204 S800
;TYPE:External perimeter
;WIDTH:0.419999
G1 F300
G1 X125.032 Y104.41 E.00883
G1 X144.922 Y104.42 E.59556
G1 X145.181 Y104.444 E.00778
M73 P40 R0
M73 Q41 S0
G1 X145.408 Y104.592 E.00813
G1 X145.556 Y104.819 E.00813
G1 X145.571 Y105.09 E.00813
G1 X145.473 Y105.344 E.00813
M73 P41 R0
G1 X145.262 Y105.515 E.00813
G1 X144.968 Y105.59 E.0091
G1 X125.079 Y105.59 E.59554
G1 X124.921 Y105.572 E.00474
M73 P49 R0
M73 Q50 S0
G1 X124.656 Y105.473 E.00848
G1 X124.486 Y105.264 E.00809
G1 X124.415 Y105 E.00817
G1 X124.508 Y104.693 E.0096
M73 P50 R0
G1 X124.701 Y104.521 E.00774
M204 S1000
G1 X124.997 Y104.635 F10800
; stop printing object ThinSewingLineLonger.stl id:0 copy 0
M106 S204
;LAYER_CHANGE
;Z:0.4
;HEIGHT:0.2
;BEFORE_LAYER_CHANGE
G92 E0.0
;0.4


G1 E-.075 F2400
;WIPE_START
G1 F8640
G1 X125.032 Y104.41 E-.09215
G1 X129.813 Y104.412 E-1.26159
;WIPE_END
G1 E-.07125 F2400
M73 Q51 S0
G1 Z.4 F720
;AFTER_LAYER_CHANGE
;0.4
M104 S210 ; set temperature
; printing object ThinSewingLineLonger.stl id:0 copy 0
G1 X124.748 Y104.924 F10800
G1 E1.501 F2400
M204 S800
;TYPE:Perimeter
;WIDTH:0.61438
M73 P51 R0
G1 F300
G1 X124.837 Y104.776 E.00782
G1 X125.056 Y104.714 E.01032
G1 X144.921 Y104.714 E.90145
G1 X145.124 Y104.756 E.0094
M73 P59 R0
M73 Q60 S0
G1 X145.244 Y104.876 E.00767
G1 X145.27 Y105.043 E.00767
G1 X145.263 Y105.086 E.00197
G1 X145.163 Y105.224 E.00776
G1 X144.944 Y105.286 E.01032
M73 P60 R0
G1 X125.079 Y105.286 E.90145
G1 X124.837 Y105.224 E.01131
M73 P68 R0
M73 Q68 S0
G1 X124.737 Y105.086 E.00776
G1 X124.744 Y104.983 E.00464
M204 S1000
G1 X124.297 Y104.7 F10800
M204 S800
;TYPE:External perimeter
;WIDTH:0.449999
G1 F300
G1 X124.466 Y104.456 E.00962
G1 X124.761 Y104.266 E.01136
M73 Q69 S0
G1 X125.018 Y104.225 E.00839
M73 P69 R0
G1 X144.921 Y104.225 E.64339
G1 X145.043 Y104.235 E.00393
M73 P77 R0
M73 Q77 S0
G1 X145.346 Y104.32 E.0102
G1 X145.539 Y104.461 E.00771
G1 X145.68 Y104.654 E.00771
G1 X145.753 Y104.881 E.00771
G1 X145.753 Y105.119 E.00771
M73 Q78 S0
G1 X145.734 Y105.239 E.00391
M73 P78 R0
G1 X145.625 Y105.454 E.00781
G1 X145.454 Y105.625 E.00781
G1 X145.239 Y105.734 E.00781
G1 X144.982 Y105.775 E.00839
G1 X125.079 Y105.775 E.64339
G1 X124.761 Y105.734 E.01034
M73 P86 R0
M73 Q86 S0
G1 X124.463 Y105.541 E.01149
M73 Q87 S0
G1 X124.314 Y105.334 E.00825
M73 P87 R0
G1 X124.229 Y105.006 E.01094
G1 X124.284 Y104.759 E.00819
M204 S1000
G1 X124.592 Y104.662 F10800
; stop printing object ThinSewingLineLonger.stl id:0 copy 0
G1 E-.075 F2400
;WIPE_START
G1 F8640;_WIPE
G1 X124.466 Y104.456 E-.0934
G1 F8640;_WIPE
G1 X124.761 Y104.266 E-.0927
G1 F8640;_WIPE
G1 X125.018 Y104.225 E-.06849
G1 F8640;_WIPE
G1 X129.183 Y104.225 E-1.09917
;WIPE_END
G1 E-.07125 F2400
M107
;TYPE:Custom
; Filament-specific end gcode
G4 ; wait
M221 S100 ; reset flow
M900 K0 ; reset LA
M907 E538 ; reset extruder motor current
M104 S0 ; turn off temperature
M140 S0 ; turn off heatbed
M107 ; turn off fan
G1 Z30.4 ; Move print head up
G1 X0 Y200 F3000 ; home X axis
M84 ; disable motors
M73 P100 R0
M73 Q100 S0
; filament used [mm] = 5.95
; filament used [cm3] = 0.01
; filament used [g] = 0.02
; filament cost = 0.00
; total filament used [g] = 0.02
; total filament cost = 0.00
; estimated printing time (normal mode) = 47s
; estimated printing time (silent mode) = 48s

; prusaslicer_config = begin
; avoid_crossing_perimeters = 0
; avoid_crossing_perimeters_max_detour = 0
; bed_custom_model = 
; bed_custom_texture = 
; bed_shape = 0x0,250x0,250x210,0x210
; bed_temperature = 60
; before_layer_gcode = ;BEFORE_LAYER_CHANGE\nG92 E0.0\n;[layer_z]\n\n
; between_objects_gcode = 
; bottom_fill_pattern = monotonic
; bottom_solid_layers = 4
; bottom_solid_min_thickness = 0.5
; bridge_acceleration = 1000
; bridge_angle = 0
; bridge_fan_speed = 100
; bridge_flow_ratio = 0.95
; bridge_speed = 25
; brim_separation = 0.1
; brim_type = outer_only
; brim_width = 0
; clip_multipart_objects = 1
; color_change_gcode = M600
; compatible_printers_condition_cummulative = "printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK3.*/ and nozzle_diameter[0]==0.4";"! (printer_notes=~/.*PRINTER_VENDOR_PRUSA3D.*/ and printer_notes=~/.*PRINTER_MODEL_MK(2.5|3).*/ and single_extruder_multi_material)"
; complete_objects = 0
; cooling = 1
; cooling_tube_length = 5
; cooling_tube_retraction = 91.5
; default_acceleration = 1000
; default_filament_profile = "Prusament PLA"
; default_print_profile = 0.15mm QUALITY @MK3
; deretract_speed = 0
; disable_fan_first_layers = 1
; dont_support_bridges = 0
; draft_shield = disabled
; duplicate_distance = 6
; elefant_foot_compensation = 0.2
; end_filament_gcode = "; Filament-specific end gcode"
; end_gcode = G4 ; wait\nM221 S100 ; reset flow\nM900 K0 ; reset LA\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3|@0.25 nozzle MK3).*/}M907 E538 ; reset extruder motor current{endif}\nM104 S0 ; turn off temperature\nM140 S0 ; turn off heatbed\nM107 ; turn off fan\n{if max_layer_z < max_print_height}G1 Z{z_offset+min(max_layer_z+30, max_print_height)}{endif} ; Move print head up\nG1 X0 Y200 F3000 ; home X axis\nM84 ; disable motors
; ensure_vertical_shell_thickness = 1
; external_perimeter_extrusion_width = 0.45
; external_perimeter_speed = 25
; external_perimeters_first = 0
; extra_loading_move = -2
; extra_perimeters = 0
; extruder_clearance_height = 20
; extruder_clearance_radius = 45
; extruder_colour = ""
; extruder_offset = 0x0
; extrusion_axis = E
; extrusion_multiplier = 0.955
; extrusion_width = 0.45
; fan_always_on = 1
; fan_below_layer_time = 60
; filament_colour = #F00000
; filament_cooling_final_speed = 3.4
; filament_cooling_initial_speed = 2.2
; filament_cooling_moves = 4
; filament_cost = 25.99
; filament_density = 1.24
; filament_diameter = 1.75
; filament_load_time = 0
; filament_loading_speed = 28
; filament_loading_speed_start = 3
; filament_max_volumetric_speed = 15
; filament_minimal_purge_on_wipe_tower = 15
; filament_notes = "Eryone Red"
; filament_ramming_parameters = "120 100 6.6 6.8 7.2 7.6 7.9 8.2 8.7 9.4 9.9 10.0| 0.05 6.6 0.45 6.8 0.95 7.8 1.45 8.3 1.95 9.7 2.45 10 2.95 7.6 3.45 7.6 3.95 7.6 4.45 7.6 4.95 7.6"
; filament_settings_id = PLA_RedEryone_LWW
; filament_soluble = 0
; filament_spool_weight = 0
; filament_toolchange_delay = 0
; filament_type = PLA
; filament_unload_time = 0
; filament_unloading_speed = 90
; filament_unloading_speed_start = 100
; filament_vendor = (Unknown)
; fill_angle = 45
; fill_density = 15%
; fill_pattern = gyroid
; first_layer_acceleration = 800
; first_layer_acceleration_over_raft = 0
; first_layer_bed_temperature = 60
; first_layer_extrusion_width = 0.42
; first_layer_height = 0.2
; first_layer_speed = 20
; first_layer_speed_over_raft = 30
; first_layer_temperature = 215
; full_fan_speed_layer = 0
; fuzzy_skin = none
; fuzzy_skin_point_dist = 0.8
; fuzzy_skin_thickness = 0.3
; gap_fill_enabled = 1
; gap_fill_speed = 40
; gcode_comments = 0
; gcode_flavor = marlin
; gcode_label_objects = 1
; gcode_resolution = 0.0125
; gcode_substitutions = 
; high_current_on_filament_swap = 0
; host_type = octoprint
; infill_acceleration = 1000
; infill_anchor = 2.5
; infill_anchor_max = 12
; infill_every_layers = 1
; infill_extruder = 1
; infill_extrusion_width = 0.45
; infill_first = 0
; infill_only_where_needed = 0
; infill_overlap = 25%
; infill_speed = 80
; inherits_cummulative = ;"Prusament PLA";"Original Prusa i3 MK3S & MK3S+"
; interface_shells = 0
; ironing = 0
; ironing_flowrate = 15%
; ironing_spacing = 0.1
; ironing_speed = 15
; ironing_type = top
; layer_gcode = ;AFTER_LAYER_CHANGE\n;[layer_z]
; layer_height = 0.2
; machine_limits_usage = emit_to_gcode
; machine_max_acceleration_e = 5000,5000
; machine_max_acceleration_extruding = 1250,1250
; machine_max_acceleration_retracting = 1250,1250
; machine_max_acceleration_travel = 1500,1250
; machine_max_acceleration_x = 1000,960
; machine_max_acceleration_y = 1000,960
; machine_max_acceleration_z = 200,200
; machine_max_feedrate_e = 120,120
; machine_max_feedrate_x = 200,100
; machine_max_feedrate_y = 200,100
; machine_max_feedrate_z = 12,12
; machine_max_jerk_e = 4.5,4.5
; machine_max_jerk_x = 8,8
; machine_max_jerk_y = 8,8
; machine_max_jerk_z = 0.4,0.4
; machine_min_extruding_rate = 0,0
; machine_min_travel_rate = 0,0
; max_fan_speed = 80
; max_layer_height = 0.3
; max_print_height = 210
; max_print_speed = 200
; max_volumetric_extrusion_rate_slope_negative = 0
; max_volumetric_extrusion_rate_slope_positive = 0
; max_volumetric_speed = 0
; min_bead_width = 85%
; min_fan_speed = 10
; min_feature_size = 25%
; min_layer_height = 0.05
; min_print_speed = 5
; min_skirt_length = 4
; mmu_segmented_region_max_width = 0
; notes = 
; nozzle_diameter = 0.4
; only_retract_when_crossing_perimeters = 0
; ooze_prevention = 0
; output_filename_format = {input_filename_base}_{layer_height}mm_{initial_filament_type}_{printer_model}_{print_time}.gcode
; overhangs = 1
; parking_pos_retraction = 92
; pause_print_gcode = M601
; perimeter_acceleration = 800
; perimeter_extruder = 1
; perimeter_extrusion_width = 0.45
; perimeter_generator = arachne
; perimeter_speed = 45
; perimeters = 2
; physical_printer_settings_id = 
; post_process = 
; print_settings_id = 0.20mm QUALITY @MK3
; printer_model = MK3S
; printer_notes = Don't remove the following keywords! These keywords are used in the "compatible printer" condition of the print and filament profiles to link the particular print and filament profiles to this printer profile.\nPRINTER_VENDOR_PRUSA3D\nPRINTER_MODEL_MK3\n
; printer_settings_id = LWW Prusa i3 MK3S & MK3S+
; printer_technology = FFF
; printer_variant = 0.4
; printer_vendor = 
; raft_contact_distance = 0.2
; raft_expansion = 1.5
; raft_first_layer_density = 90%
; raft_first_layer_expansion = 3
; raft_layers = 0
; remaining_times = 1
; resolution = 0
; retract_before_travel = 2
; retract_before_wipe = 5%
; retract_layer_change = 1
; retract_length = 1.5
; retract_length_toolchange = 4
; retract_lift = 0
; retract_lift_above = 0
; retract_lift_below = 209
; retract_restart_extra = 0.001
; retract_restart_extra_toolchange = 0
; retract_speed = 40
; seam_position = aligned
; silent_mode = 1
; single_extruder_multi_material = 0
; single_extruder_multi_material_priming = 0
; skirt_distance = 2
; skirt_height = 3
; skirts = 0
; slice_closing_radius = 0.049
; slicing_mode = regular
; slowdown_below_layer_time = 25
; small_perimeter_speed = 25
; solid_infill_below_area = 0
; solid_infill_every_layers = 0
; solid_infill_extruder = 1
; solid_infill_extrusion_width = 0.45
; solid_infill_speed = 80
; spiral_vase = 0
; standby_temperature_delta = -5
; start_filament_gcode = "M900 K{if printer_notes=~/.*PRINTER_MODEL_MINI.*/ and nozzle_diameter[0]==0.6}0.12{elsif printer_notes=~/.*PRINTER_MODEL_MINI.*/}0.2{elsif printer_notes=~/.*PRINTER_HAS_BOWDEN.*/}200{elsif nozzle_diameter[0]==0.6}18{else}30{endif} ; Filament gcode"
; start_gcode = M862.3 P "[printer_model]" ; printer model check\nM862.1 P[nozzle_diameter] ; nozzle diameter check\nM115 U3.9.3 ; tell printer latest fw version\nG90 ; use absolute coordinates\nM83 ; extruder relative mode\nM104 S[first_layer_temperature] ; set extruder temp\nM140 S[first_layer_bed_temperature] ; set bed temp\nM190 S[first_layer_bed_temperature] ; wait for bed temp\nM109 S[first_layer_temperature] ; wait for extruder temp\nG28 W ; home all without mesh bed level\nG80 ; mesh bed leveling\nG1 Y-3.0 F1000.0 ; go outside print area\nG92 E0.0\nG1 X60.0 E9.0 F1000.0 ; intro line\nG1 X100.0 E12.5 F1000.0 ; intro line\nG92 E0.0\nM221 S{if layer_height<0.075}100{else}95{endif}\n\n; Don't change E values below. Excessive value can damage the printer.\n{if print_settings_id=~/.*(DETAIL @MK3|QUALITY @MK3).*/}M907 E430 ; set extruder motor current{endif}\n{if print_settings_id=~/.*(SPEED @MK3|DRAFT @MK3).*/}M907 E538 ; set extruder motor current{endif}
; support_material = 0
; support_material_angle = 0
; support_material_auto = 1
; support_material_bottom_contact_distance = 0
; support_material_bottom_interface_layers = 0
; support_material_buildplate_only = 0
; support_material_closing_radius = 2
; support_material_contact_distance = 0.2
; support_material_enforce_layers = 0
; support_material_extruder = 0
; support_material_extrusion_width = 0.35
; support_material_interface_contact_loops = 0
; support_material_interface_extruder = 0
; support_material_interface_layers = 2
; support_material_interface_pattern = rectilinear
; support_material_interface_spacing = 0.2
; support_material_interface_speed = 80%
; support_material_pattern = rectilinear
; support_material_spacing = 2
; support_material_speed = 50
; support_material_style = grid
; support_material_synchronize_layers = 0
; support_material_threshold = 50
; support_material_with_sheath = 0
; support_material_xy_spacing = 60%
; temperature = 210
; template_custom_gcode = 
; thick_bridges = 0
; thin_walls = 0
; threads = 24
; thumbnails = 
; thumbnails_format = PNG
; toolchange_gcode = 
; top_fill_pattern = monotonic
; top_infill_extrusion_width = 0.4
; top_solid_infill_speed = 40
; top_solid_layers = 6
; top_solid_min_thickness = 0.7
; travel_speed = 180
; travel_speed_z = 12
; use_firmware_retraction = 0
; use_relative_e_distances = 1
; use_volumetric_e = 0
; variable_layer_height = 1
; wall_distribution_count = 1
; wall_transition_angle = 10
; wall_transition_filter_deviation = 25%
; wall_transition_length = 0.4
; wipe = 1
; wipe_into_infill = 0
; wipe_into_objects = 0
; wipe_tower = 1
; wipe_tower_bridging = 10
; wipe_tower_brim_width = 2
; wipe_tower_no_sparse_layers = 0
; wipe_tower_rotation_angle = 0
; wipe_tower_width = 60
; wipe_tower_x = 170
; wipe_tower_y = 125
; wiping_volumes_extruders = 70,70
; wiping_volumes_matrix = 0
; xy_size_compensation = 0
; z_offset = 0
; prusaslicer_config = end
